name: Docker Build CI/CD

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      # - name: "Login via Azure CLI"
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build \
            -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-pizza-maker:latest \
            --build-arg VITE_APIM_SUBSCRIPTION_KEY=${{ secrets.VITE_APIM_SUBSCRIPTION_KEY }} \
            --build-arg VITE_APIM_LOGIC_URL=${{ secrets.VITE_APIM_LOGIC_URL }} \
            --no-cache . 
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/azure-pizza-maker:latest
        env:
          VITE_APIM_SUBSCRIPTION_KEY: ${{ secrets.VITE_APIM_SUBSCRIPTION_KEY }}
          VITE_APIM_LOGIC_URL: ${{ secrets.VITE_APIM_LOGIC_URL }}

      # - name: "Deploy to Azure Container Instances"
      #   uses: "azure/aci-deploy@v1"
      #   with:
      #     resource-group: ${{ secrets.RESOURCE_GROUP }}
      #     dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
      #     image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
      #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
      #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #     name: aci-sampleapp
      #     location: "west us"
